
package vehicle_reservation_system;
import java.io.*;
import java.util.Scanner;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

public class parking1 extends javax.swing.JFrame {
    /**
     * Creates new form parking1
     */
    public parking1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        space1 = new javax.swing.JButton();
        space2 = new javax.swing.JButton();
        space3 = new javax.swing.JButton();
        space4 = new javax.swing.JButton();
        space5 = new javax.swing.JButton();
        space6 = new javax.swing.JButton();
        space7 = new javax.swing.JButton();
        space8 = new javax.swing.JButton();
        space9 = new javax.swing.JButton();
        space10 = new javax.swing.JButton();
        space11 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("EXIT");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("ENTRANCE");

        space1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space1.setText("1");
        space1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1ActionPerformed(evt);
            }
        });

        space2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space2.setText("2");
        space2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space2ActionPerformed(evt);
            }
        });

        space3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space3.setText("3");
        space3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space3ActionPerformed(evt);
            }
        });

        space4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space4.setText("4");
        space4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space4ActionPerformed(evt);
            }
        });

        space5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space5.setText("5");
        space5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space5ActionPerformed(evt);
            }
        });

        space6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space6.setText("7");
        space6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space6ActionPerformed(evt);
            }
        });

        space7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space7.setText("6");
        space7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space7ActionPerformed(evt);
            }
        });

        space8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space8.setText("8");
        space8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space8ActionPerformed(evt);
            }
        });

        space9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space9.setText("9");
        space9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space9ActionPerformed(evt);
            }
        });

        space10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space10.setText("10");
        space10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space10ActionPerformed(evt);
            }
        });

        space11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        space11.setText("11");
        space11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space11ActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(96, 96, 96))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(space1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(space2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(space3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(space4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(space5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(space7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(space6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(space8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(space9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(space10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(space11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(space1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("PLEASE CHOOSE YOUR PARKING SPACE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/* space refers to the parking spaces
    */
    private void space1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1ActionPerformed
    try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space1.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){ //"0" means the slot is available."1" means it is unavailable
                               //If someone has booked the slot, then the next user cannot book the particular slot
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p1 = new parking1();
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
            space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
            space11.setEnabled(false);
            FileWriter space1;
            space1 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space1.txt");
            space1.write("1");
            space1.close();
            scanner.close();
        }
        else{
                space1.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
        
        
        
    }//GEN-LAST:event_space1ActionPerformed

    private void space2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space2ActionPerformed
        // TODO add your handling code here:
            try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space2.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p2 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space2;
            space2 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space2.txt");
            space2.write("1");
            space2.close();
            scanner.close();
        }
        else{
                space2.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space2ActionPerformed

    private void space3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space3ActionPerformed
        // TODO add your handling code here:
            try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space3.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p3 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space3;
            space3 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space3.txt");
            space3.write("1");
            space3.close();
            scanner.close();
        }
        else{
                space3.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space3ActionPerformed

    private void space4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space4ActionPerformed
        // TODO add your handling code here:
            try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space4.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p4 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space4;
            space4 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space4.txt");
            space4.write("1");
            space4.close();
            scanner.close();
        }
        else{
                space4.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space4ActionPerformed

    private void space5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space5ActionPerformed
        // TODO add your handling code here:
            try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space5.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p5 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space5;
            space5 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space5.txt");
            space5.write("1");
            space5.close();
            scanner.close();
        }
        else{
                space5.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }

    }//GEN-LAST:event_space5ActionPerformed

    private void space7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space7ActionPerformed
        // TODO add your handling code here:
            try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space7.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p7 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space7;
            space7 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space7.txt");
            space7.write("1");
            space7.close();
            scanner.close();
        }
        else{
                space7.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space7ActionPerformed

    private void space6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space6ActionPerformed
        // TODO add your handling code here:
        try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space6.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p6 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space6;
            space6 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space6.txt");
            space6.write("1");
            space6.close();
            scanner.close();
        }
        else{
                space6.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space6ActionPerformed

    private void space8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space8ActionPerformed
        // TODO add your handling code here:
        try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space8.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p8 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space8;
            space8 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space8.txt");
            space8.write("1");
            space8.close();
            scanner.close();
        }
        else{
                space8.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space8ActionPerformed

    private void space9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space9ActionPerformed
        // TODO add your handling code here:
        try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space9.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p9 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space9;
            space9 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space9.txt");
            space9.write("1");
            space9.close();
            scanner.close();
        }
        else{
                space9.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space9ActionPerformed

    private void space10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space10ActionPerformed
        // TODO add your handling code here:
        try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space10.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p10 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space10;
            space10 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space10.txt");
            space10.write("1");
            space10.close();
            scanner.close();
        }
        else{
                space10.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space10ActionPerformed

    private void space11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space11ActionPerformed
        // TODO add your handling code here:
        try{
        Path path = Paths.get("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space11.txt");
        Scanner scanner = new Scanner(path);
        String line = scanner.nextLine();
        if("0".equals(line)){
            JOptionPane.showMessageDialog(null, "Slot available.");
            parking1 p11 = new parking1();
       
            space1.setEnabled(false);
            space2.setEnabled(false);
            space3.setEnabled(false);
            space4.setEnabled(false);
            space5.setEnabled(false);
            space6.setEnabled(false);
            space7.setEnabled(false);
 	    space8.setEnabled(false);
            space9.setEnabled(false);
            space10.setEnabled(false);
      	    space11.setEnabled(false);
            FileWriter space11;
            space11 = new FileWriter("C:\\Users\\joey_\\Desktop\\Vehicles-Reservation-System\\Vehicles-Reservation-System\\Vehicles Reservation System\\src\\vehicle_reservation_system\\space\\space11.txt");
            space11.write("1");
            space11.close();
            scanner.close();
        }
        else{
                space11.setEnabled(false);     
                JOptionPane.showMessageDialog(null, "Slot not available."); 
                 scanner.close();
            }    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "File not exist.");
    }
    }//GEN-LAST:event_space11ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        if(!space1.isEnabled()||!space2.isEnabled()||!space3.isEnabled()||!space4.isEnabled()||!space5.isEnabled()||!space6.isEnabled()||!space7.isEnabled()||!space8.isEnabled()||!space9.isEnabled()||!space10.isEnabled()||!space11.isEnabled()){
        dispose();
        parking2 s= new parking2();
        s.setVisible(true);
        }
    }//GEN-LAST:event_nextActionPerformed
// Go to the previous page
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dispose();
        VehicleUI s=new VehicleUI();
        s.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parking1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parking1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton next;
    private javax.swing.JButton space1;
    private javax.swing.JButton space10;
    private javax.swing.JButton space11;
    private javax.swing.JButton space2;
    private javax.swing.JButton space3;
    private javax.swing.JButton space4;
    private javax.swing.JButton space5;
    private javax.swing.JButton space6;
    private javax.swing.JButton space7;
    private javax.swing.JButton space8;
    private javax.swing.JButton space9;
    // End of variables declaration//GEN-END:variables
}
